[package]
name = "auriumchain"
version = "1.0.0"
edition = "2021"
authors = ["AuriumChain Developers"]
description = "AuriumChain - Fast, Eco-Efficient, Autonomous Blockchain"
license = "MIT"

[dependencies]
# Async runtime
tokio = { version = "1.40", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Cryptography
sha2 = "0.10"
blake3 = "1.5"
secp256k1 = { version = "0.29", features = ["rand", "global-context"] }
ripemd = "0.1"
rand = "0.8"

# Network
libp2p = { version = "0.53", features = ["tcp", "mdns", "noise", "yamux", "gossipsub"] }

# Storage
rocksdb = "0.22"

# Web/RPC
axum = "0.7"
tower-http = { version = "0.5", features = ["cors"] }

# CLI
clap = { version = "4.5", features = ["derive"] }

# Utilities
chrono = "0.4"
hex = "0.4"
log = "0.4"
env_logger = "0.11"
thiserror = "1.0"
anyhow = "1.0"
bs58 = "0.5"
bincode = "1.3"

[dev-dependencies]
criterion = "0.5"

[[bin]]
name = "auriumchain"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
